### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by devfoo-one** [devfoo-one/WS16_MMP-Video-2#1]
- [x] Bildfilter in beide Video Darstellungen von Aufgabe 1 integrieren (Video-File und Kamera)
   - [x] Blur/Mittelwertfilter
   - [x] Gauss
   - [x] Prewitt
- [ ] BONUS: WebGL-Pixelshader verwenden
- [x] Website
- [x] Kurzbeschreibung (txt/pdf)

**Comment by devfoo-one** [comment]
Aufgabe V2: Bild-Filter

Erstelle folgende Bildfilter mit 3x3-Filterkern:

a - Blur/Mittelwertfilter

b - Gauss

c - Prewitt

Beispiele:

https://www.html5rocks.com/en/tutorials/canvas/imagefilters/

Bonus:

d - verwende WebGL-Pixelshader wie z.B. in 

http://evanw.github.io/glfx.js/

http://phoboslab.org/log/2013/11/fast-image-filters-with-webgl

Binde die Filter in die Video-Darstellung von Aufgabe 1 ein! (Video-File und Kamera)
Abgabe: 

ZIP im Format mmp2016-name-a2.zip mit Kurzbeschreibung (txt/pdf)

Screenshots der Filter angewendet auf der Webseite

und HTML-Seite sowie Link zu HTML-Seite online

**Comment by devfoo-one** [comment]
http://public.beuth-hochschule.de/~s67655/mmp_video/ue2-filters/filters/filters.html
